version: '3.9'

services:
  php:
    image: php:8.1-apache
    container_name: line_bot_php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: php:80
      NGROK_AUTH: AUTH_TOKEN
    depends_on:
      - php
