version: '3.9'

services:
  php:
    image: php:v1
    build: ./dockerfile/php
    container_name: line_bot_php
    ports:
      - 80:80
    volumes:
      - ./dockerfile/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
      
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: php:80
    depends_on:
      - php
    env_file:
      - .env
