version: '3.9'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: line_bot_phpl
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  ngrok:
    build:
      context: ./docker/ngrok
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4040:4040
    command: ["http", "php:80"]
    environment:
      NGROK_AUTHTOKEN: AUTH_TOKEN
    depends_on:
      - php
